name: Deploy to Firebase Hosting Beta
on:
  push:
    branches:
      - beta
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: CI=false npm run build:beta
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAPZAP_ME }}
          channelId: beta
          projectId: zapzap-me
          target: beta
